# Problem 1

In [15]:
import numpy as np # 1 - numpy kütüphanesini import edin

a = np.random.randint(0,10,5) # 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
print(a)

print(a.ndim)# 3 - matris'in boyutunu öğrenin

print(a.reshape([5,1]))# 4 - matris'i yeniden boyutlandırın

print(a.shape) # 5 - matris'in boyut sayısını öğrenin


[7 7 2 8 9]
1
[[7]
 [7]
 [2]
 [8]
 [9]]
(5,)


# Problem 2

In [22]:
b = np.array([1,3,5,7,9])  # 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
print(b)
print(np.split(b, [2,4]))# 2 - Oluşturduğunuz matrisi parçalayın

print(np.concatenate([b,b]))# 3 - Parçalanmış matrisleri birleştirin


[1 3 5 7 9]
[array([1, 3]), array([5, 7]), array([9])]
[1 3 5 7 9 1 3 5 7 9]


# Problem 3

In [38]:
c = np.arange(5,101,2)
x = np.random.choice(c, 10)
 # 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
print(x)

print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)# 2 - matris'in özelliklerini inceleyin


[21 91  5 95 97 71 99 67 33 81]
1
(10,)
10
int64
