# Problem 1 

In [7]:
import numpy as np

new = np.array([1,3,4,2,7,8,4]) # 2 - 5 elemanlı bir numpy array oluşturun
print(new)
new.sort()
print(new) # 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.


[1 3 4 2 7 8 4]
[1 2 3 4 4 7 8]


# Problem 2

In [42]:
a = np.array([10,15,30,45,60]) # 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
print(a)

b = np.arange(5,15) # 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
print(b) 

c = np.arange(50,100,5) # 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
print(c)

d = np.zeros(10) # 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
print(d)

e = np.ones(10) # 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
print(e)

f = np.linspace(0,100,5) # 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
print(f)

g = np.random.randint(10,30,5) # 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
print(g)

h = np.random.uniform(-1,1,10) # 8- [-1 ile 1] arasında 10 adet sayı üretin.
print(h)

i = np.random.randint(10,50,(3,5))
 # 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
print(i)

satirToplam = i.sum(axis = 1) # 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
sutunToplam = i.sum(axis = 0)
print("Satir toplami :" , satirToplam)
print("Sutun toplami :" , sutunToplam)

print("En buyuk sayi:" , i.max()) # 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print('En kucuk sayi:', i.min())
print("Ortalama:", i.mean())


print("En buyuk deger indexi: " , np.argmax(i)) # 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


j = np.arange(10, 20) # 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
jj = j.reshape(2,5)
print(jj)
print("---")
print(jj[:3])

print(jj[::-1])# 14- Üretilen dizinin elemanlarını tersten yazdırın.


print(jj[0,:]) # 15- Üretilen matrisin ilk satırını seçiniz.


print(jj[1,2]) # 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


print(jj[:,0])# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


print(np.power(jj,2))# 18- Üretilen matrisin her bir elemanının karesini alınız.


k = np.arange(-50, 50, 2) 
print(k[k>0]) # 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[25 12 28 28 11]
[-0.83916434 -0.49099232  0.71016506 -0.4905925   0.22874705  0.10996269
  0.11373283  0.81658069  0.1360025  -0.40601889]
[[30 47 40 27 35]
 [34 26 27 34 34]
 [20 32 32 21 13]]
Satir toplami : [179 155 118]
Sutun toplami : [ 84 105  99  82  82]
En buyuk sayi: 47
En kucuk sayi: 13
Ortalama: 30.133333333333333
En buyuk deger indexi:  1
[[10 11 12 13 14]
 [15 16 17 18 19]]
---
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[15 16 17 18 19]
 [10 11 12 13 14]]
[10 11 12 13 14]
17
[10 15]
[[100 121 144 169 196]
 [225 256 289 324 361]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
